### ISSUE TITLE
Bilateral smoothing error code

### ISSUE THREAD

**Issue by buddybu** [Piemontez/opencvflow#3]
Adding a bilateral and linking it to the file input source, does not smooth the image as expected, instead I get an error code that is different each time I run the code.  I've tried others and they work as expected.   Do I need to do something before using the bilateral filter?

**Comment by Piemontez** [comment]
I will investigate the error.
The Code has recently been refactored, and I'm working on improving the display errors and focusing more on documentation.

**Comment by Piemontez** [comment]
I refactored the system, and identified several places in the system that needed to be added to remove the matrices (Mat) from opencv.js according to its own documentation. This caused components to die unexpectedly.

However, an important item here, as part of the tool is a bind to opencv, most of the errors shown on screen come from the opencv.js library.

The "code XXXXX" error can occur for several reasons, such as connecting the output of components to inputs of other that are not compatible, or even not converting images into grayscale, before connecting to a component that expects images with a single channel.

To prevent this, we will have to place a validator of possible links between components. This type of validation is not yet on the current priority list. Only simpler validations were mapped. :/

**Comment by buddybu** [comment]
@Piemontez Thank you for the update.  I very much appreciate the information!
