### ISSUE TITLE
Normalize is missing `normType` option

### ISSUE THREAD

**Issue by cmahnke** [Piemontez/opencvflow#5]
I'm not sure if I'm missing something but it seems that the provided options for `normalize` are wrong. According to the interface (see screenshot) the options provided for `normalize`, parameter `normType` are the enum from `enum cv::DistanceTypes`. My expectation where those provided by [`cv::NormTypes`](https://docs.opencv.org/4.x/d2/de8/group__core__array.html#gad12cefbcb5291cf958a85b4b67b6149f)

<img width="606" alt="Bildschirmfoto 2024-03-31 um 13 40 39" src="https://github.com/Piemontez/opencvflow/assets/194820/63c15a98-7b76-4352-ad93-19ed4ebb9b07">

**Comment by Piemontez** [comment]
Correct, I will be fixing this as soon as possible.

**Comment by Piemontez** [comment]
Fixed on version 0.10.2. 

Now, modal show fallow options:
  NORM_INF = 1,
  NORM_L1 = 2,
  NORM_L2 = 4,
  NORM_L2SQR = 5,
  NORM_HAMMING = 6,
  NORM_HAMMING2 = 7,
  NORM_TYPE_MASK = 7,
  NORM_RELATIVE = 8,
  NORM_MINMAX = 32,
